name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: Build web
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.7.7
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

      - name: Archive web build
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: build/web